// flow-typed signature: 00dcf4dc7187f21fb03c66249f2b90d5
// flow-typed version: <<STUB>>/react-interactive_v^0.8.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-interactive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-interactive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-interactive/dist/ReactInteractive' {
  declare module.exports: any;
}

declare module 'react-interactive/dist/ReactInteractive.min' {
  declare module.exports: any;
}

declare module 'react-interactive/lib/compareProps' {
  declare module.exports: any;
}

declare module 'react-interactive/lib/constants' {
  declare module.exports: any;
}

declare module 'react-interactive/lib/extractStyle' {
  declare module.exports: any;
}

declare module 'react-interactive/lib/index' {
  declare module.exports: any;
}

declare module 'react-interactive/lib/inputTracker' {
  declare module.exports: any;
}

declare module 'react-interactive/lib/mergeAndExtractProps' {
  declare module.exports: any;
}

declare module 'react-interactive/lib/notifier' {
  declare module.exports: any;
}

declare module 'react-interactive/lib/propTypes' {
  declare module.exports: any;
}

declare module 'react-interactive/lib/recursiveNodeCheck' {
  declare module.exports: any;
}

declare module 'react-interactive/lib/syntheticClick' {
  declare module.exports: any;
}

declare module 'react-interactive/src/compareProps' {
  declare module.exports: any;
}

declare module 'react-interactive/src/constants' {
  declare module.exports: any;
}

declare module 'react-interactive/src/extractStyle' {
  declare module.exports: any;
}

declare module 'react-interactive/src/index' {
  declare module.exports: any;
}

declare module 'react-interactive/src/inputTracker' {
  declare module.exports: any;
}

declare module 'react-interactive/src/mergeAndExtractProps' {
  declare module.exports: any;
}

declare module 'react-interactive/src/notifier' {
  declare module.exports: any;
}

declare module 'react-interactive/src/propTypes' {
  declare module.exports: any;
}

declare module 'react-interactive/src/recursiveNodeCheck' {
  declare module.exports: any;
}

declare module 'react-interactive/src/syntheticClick' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-interactive/dist/ReactInteractive.js' {
  declare module.exports: $Exports<'react-interactive/dist/ReactInteractive'>;
}
declare module 'react-interactive/dist/ReactInteractive.min.js' {
  declare module.exports: $Exports<'react-interactive/dist/ReactInteractive.min'>;
}
declare module 'react-interactive/lib/compareProps.js' {
  declare module.exports: $Exports<'react-interactive/lib/compareProps'>;
}
declare module 'react-interactive/lib/constants.js' {
  declare module.exports: $Exports<'react-interactive/lib/constants'>;
}
declare module 'react-interactive/lib/extractStyle.js' {
  declare module.exports: $Exports<'react-interactive/lib/extractStyle'>;
}
declare module 'react-interactive/lib/index.js' {
  declare module.exports: $Exports<'react-interactive/lib/index'>;
}
declare module 'react-interactive/lib/inputTracker.js' {
  declare module.exports: $Exports<'react-interactive/lib/inputTracker'>;
}
declare module 'react-interactive/lib/mergeAndExtractProps.js' {
  declare module.exports: $Exports<'react-interactive/lib/mergeAndExtractProps'>;
}
declare module 'react-interactive/lib/notifier.js' {
  declare module.exports: $Exports<'react-interactive/lib/notifier'>;
}
declare module 'react-interactive/lib/propTypes.js' {
  declare module.exports: $Exports<'react-interactive/lib/propTypes'>;
}
declare module 'react-interactive/lib/recursiveNodeCheck.js' {
  declare module.exports: $Exports<'react-interactive/lib/recursiveNodeCheck'>;
}
declare module 'react-interactive/lib/syntheticClick.js' {
  declare module.exports: $Exports<'react-interactive/lib/syntheticClick'>;
}
declare module 'react-interactive/src/compareProps.js' {
  declare module.exports: $Exports<'react-interactive/src/compareProps'>;
}
declare module 'react-interactive/src/constants.js' {
  declare module.exports: $Exports<'react-interactive/src/constants'>;
}
declare module 'react-interactive/src/extractStyle.js' {
  declare module.exports: $Exports<'react-interactive/src/extractStyle'>;
}
declare module 'react-interactive/src/index.js' {
  declare module.exports: $Exports<'react-interactive/src/index'>;
}
declare module 'react-interactive/src/inputTracker.js' {
  declare module.exports: $Exports<'react-interactive/src/inputTracker'>;
}
declare module 'react-interactive/src/mergeAndExtractProps.js' {
  declare module.exports: $Exports<'react-interactive/src/mergeAndExtractProps'>;
}
declare module 'react-interactive/src/notifier.js' {
  declare module.exports: $Exports<'react-interactive/src/notifier'>;
}
declare module 'react-interactive/src/propTypes.js' {
  declare module.exports: $Exports<'react-interactive/src/propTypes'>;
}
declare module 'react-interactive/src/recursiveNodeCheck.js' {
  declare module.exports: $Exports<'react-interactive/src/recursiveNodeCheck'>;
}
declare module 'react-interactive/src/syntheticClick.js' {
  declare module.exports: $Exports<'react-interactive/src/syntheticClick'>;
}
